/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData favorite = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up = IconData(0xf0aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down = IconData(0xf0ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_alt_circle_left = IconData(0xf359, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_alt_circle_right = IconData(0xf35a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xf4ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
